version: '3.8'

services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  identity-service:
    build: ./backend/services/identity-service
    container_name: fghub-identity-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  media-service:
    build: ./backend/services/media-service
    container_name: fghub-media-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  recommendation-service:
    build: ./backend/services/recommendation-service
    container_name: fghub-recommendation-service
    environment:
      - MEDIA_SERVICE_URL=http://media-service:8082
    depends_on:
      - media-service

  api-gateway:
    build: ./backend/services/api-gateway
    container_name: fghub-api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - identity-service
      - media-service
      - recommendation-service

  frontend:
    build: ./frontend
    container_name: fghub-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

volumes:
  mongo_data:
