Spring.Servlet.multipart.max-file-size=100MB
Spring.Servlet.multipart.max-request-size=100MB
server.port=9090
spring.data.mongodb.uri=mongodb://localhost:27017/fghub
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/fghub}  